apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubescope-backend
  namespace: kubescope-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubescope-backend
  template:
    metadata:
      labels:
        app: kubescope-backend
    spec:
      serviceAccountName: kubescope-account
      containers:
        - name: backend
          image: tonyq2k3/kubescope-backend:v1.0.2
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 80
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"