apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubescope-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubescope.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: kubescope-backend
  template:
    metadata:
      labels:
        app: kubescope-backend
    spec:
      serviceAccountName: kubescope-account
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          ports:
          - containerPort: 80
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"