apiVersion: v1
kind: Service
metadata:
  name: kubescope-backend
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: kubescope-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80