apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubescope-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubescope.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: kubescope-frontend
  template:
    metadata:
      labels:
        app: kubescope-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          ports:
          - containerPort: 80
          resources:
            requests:
              cpu: "300m"
              memory: "500Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"