apiVersion: v1
kind: Service
metadata:
  name: kubescope-frontend
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: kubescope-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80