# General configuration
global:
  image:
    pullPolicy: IfNotPresent

# Dashboard front-end Image
frontend:
  image:
    repository: tonyq2k3/kubescope-frontend
    tag: "v1.0.1"
  replicas: 1

# Dashboard back-end Image
backend:
  image:
    repository: tonyq2k3/kubescope-backend
    tag: "v1.0.1"
  replicas: 1