apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubescope-account
  namespace: kubescope-dashboard

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubescope-clusterrole
  namespace: kubescope-dashboard
rules:
- apiGroups: [""]
  resources:
  - pods
  - services
  - nodes
  - configmaps
  - secrets
  verbs: ["get", "watch", "list"]
- apiGroups:
  - apps
  resources:
  - deployments
  verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-secrets-global
  namespace: kubescope-dashboard
subjects:
- kind: ServiceAccount
  name: kubescope-account
  namespace: kubescope-dashboard
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubescope-clusterrole
  