apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubescope-account
  namespace: kubescope-dashboard

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubescope-clusterrole
  namespace: kubescope-dashboard
rules:
- apiGroups: [""]
  resources:
  - pods
  - namespaces
  - services
  - nodes
  - configmaps
  - secrets
  - events
  - persistentvolumes
  - persistentvolumeclaims
  verbs: ["get", "watch", "list", "create", "delete", "update", "patch"]

- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  - daemonsets
  - replicasets
  verbs: ["get", "watch", "list", "create", "delete", "update", "patch"]

- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs: ["get", "watch", "list", "create", "delete", "update", "patch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-secrets-global
  namespace: kubescope-dashboard
subjects:
- kind: ServiceAccount
  name: kubescope-account
  namespace: kubescope-dashboard
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubescope-clusterrole
  